/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface SideDrawer {
    'close': () => void;
    'open': () => void;
    'show': boolean;
    'title': string;
  }
  interface SideDrawerAttributes extends StencilHTMLAttributes {
    'show'?: boolean;
    'title'?: string;
  }

  interface DmTooltip {
    'msg': string;
  }
  interface DmTooltipAttributes extends StencilHTMLAttributes {
    'msg'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MyComponent': Components.MyComponent;
    'SideDrawer': Components.SideDrawer;
    'DmTooltip': Components.DmTooltip;
  }

  interface StencilIntrinsicElements {
    'my-component': Components.MyComponentAttributes;
    'side-drawer': Components.SideDrawerAttributes;
    'dm-tooltip': Components.DmTooltipAttributes;
  }


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLSideDrawerElement extends Components.SideDrawer, HTMLStencilElement {}
  var HTMLSideDrawerElement: {
    prototype: HTMLSideDrawerElement;
    new (): HTMLSideDrawerElement;
  };

  interface HTMLDmTooltipElement extends Components.DmTooltip, HTMLStencilElement {}
  var HTMLDmTooltipElement: {
    prototype: HTMLDmTooltipElement;
    new (): HTMLDmTooltipElement;
  };

  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement
    'side-drawer': HTMLSideDrawerElement
    'dm-tooltip': HTMLDmTooltipElement
  }

  interface ElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'side-drawer': HTMLSideDrawerElement;
    'dm-tooltip': HTMLDmTooltipElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
